dataset:
    train:
        batch_size: 32
    test:
        batch_size: 32
scheduler:
    # cifar10 num_exaples: 50_000
    # (50_000 // 32) * 90 epochs
    steps: 140_580
    params:
        boundaries: [42_174, 84_348, 112_464]
        values: [3e-2, 3e-3, 3e-4, 3e-5]